trigger: none

pr: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  - template: ./Tags.variables.yml

stages:
  - stage: get
    displayName: 'Get Tags'
    jobs:
      - job: get_tags
        displayName: 'Generate and upload Excel file'
        steps:
        - task: UsePythonVersion@0
          displayName: 'Use Python verison 3.8'
          inputs:
            versionSpec: '3.8'
        - script: pip install -r requirements.txt
          displayName: 'Install Python Modules'
        - task: AzureCLI@2
          displayName: 'Create Excel file'
          inputs:
            azureSubscription: $(SERVICECONNECTION)
            scriptType: bash
            workingDirectory: $(System.DefaultWorkingDirectory)
            scriptLocation: inlineScript
            inlineScript: |
              export ARM_CLIENT_ID=$(ARM_CLIENT_ID)
              export ARM_CLIENT_SECRET=$(ARM_CLIENT_SECRET)
              export ARM_TENANT_ID=$(ARM_TENANT_ID)
              export ARM_SUBSCRIPTION_ID=$(ARM_SUBSCRIPTION_ID)
              python3 main.py "Azure" "get" $(ARM_SUBSCRIPTION_ID)
              ls -ltrh
        - task: AzureCLI@2
          displayName: 'Upload Excel File'
          inputs:
            azureSubscription: $(SERVICECONNECTION)
            scriptType: bash
            scriptLocation: inlineScript
            inlineScript: |
              export ARM_ACCESS_KEY=$(ARM_ACCESS_KEY)
              export SA_NAME=$(SA_NAME)
              export CONTAINER_NAME=$(CONTAINER_NAME)
              export ARM_SUBSCRIPTION_ID=$(ARM_SUBSCRIPTION_ID)
              today=`date +%F`
              ls -ltrh
              az storage blob upload --account-name $(SA_NAME) --container-name "$(CONTAINER_NAME)/Report-$today" --account-key $(ARM_ACCESS_KEY) --file "$(Build.SourcesDirectory)/Reports.xlsx" --name "$(ReportsFileNamePrefix)-$(ARM_SUBSCRIPTION_ID)-$today.xlsx" --overwrite true        